### ISSUE TITLE
EPG not updating using cron command

### ISSUE THREAD

**Issue by fdotcico** [iptv-org/epg#2190]
### Describe your issue

Hi guys, I came across this project and want to start using it to implement epg in my Plex + xteve iptv.

My goal is to run this project in a container on my NAS through Portainer, so that I can serve the epg xml in xteve.

I was able to get it working, but to enable the update I am forced to restart the container each time. This is because even if I use the string --cron"@hourly" the container tries to update the epg list for only the two-day window in which I started the container.

I would like this update to be rolling and then download the new guide every day.

I am currently using this:

**Dockerfile**

```
FROM node:current-alpine3.17

RUN apk update && \
    apk add --no-cache bash git && \
    adduser -D -s /bin/bash epg_grabber

RUN mkdir /opt/epg_grabber && \
    chown epg_grabber /opt/epg_grabber

USER epg_grabber
WORKDIR /opt/epg_grabber/

RUN git clone --depth 1 -b master https://github.com/iptv-org/epg.git /opt/epg_grabber/epg && \
    cd /opt/epg_grabber/epg && \
    npm install

EXPOSE 3000
```

**start.sh**
```
#!/bin/bash

npm --prefix /opt/epg_grabber/epg run grab -- --channels=custom_channels.xml --cron="5 6,9,12,15,18,21,0 * * *" &
npm --prefix /opt/epg_grabber/epg run serve
```

**docker-compose**
```
version: '3'
services:
  epg_grabber:
    container_name: EPG-Grabber
    image: epg_grabber:latest
    environment:
      - TZ=Europe/Rome
    volumes:
      - /volume1/..../epg/start.sh:/opt/epg_grabber/start.sh
      - /volume1/..../epg/custom_channels.xml:/opt/epg_grabber/epg/custom_channels.xml
    command: bash -c "/opt/epg_grabber/start.sh"
    ports:
      - "3000:3000"
```

Thanks!
